supportedPlayers:
  - rhythmbox
  - spotify
outputDir: /tmp/conky
# album art
albumArtDir: ~/conky/monochrome/java/albumArt
albumCacheSize: 1000000   # size in kb, once breached album art images will be deleted
