system: laptop  # default value, overriden by freemarker java app

networkDevices:
  desktop:
    - name: enp0s25
      type: ethernet  
  laptop:
    - name: wlp4s0
      type: wifi
    - name: enp6s0
      type: ethernet
        
hardDisks:
  desktop:
    - device: sda
      readSpeed: 200000
      writeSpeed: 280000
      hwmonIndex: 1     # optional | linux hardware monitor index, ex. hwmon3
      partitions:
        - name: fedora
          path: /
          icon: root
        - name: home
          path: /home
          icon: home
    - device: sdb
      readSpeed: 6000
      writeSpeed: 250000
      hwmonIndex: 2
      partitions:
        - name: veronica
          path: /media/veronica
          icon: partition
    - device: sdd
      readSpeed: 6000
      writeSpeed: 250000
      hwmonIndex: 3
      partitions:
        - name: betty
          path: /media/betty
          icon: partition
    - device: sde1
      readSpeed: 6000
      writeSpeed: 60000
      name: maxtor      # optional | name to append to the output file name, ex. disk-maxtor
      partitions:
        - name: maxtor
          path: /run/media/ernesto/MAXTOR
          icon: usbdrive
threshold:
  cpu: 90
  mem: 85
  swap: 70
  tempCPU: 78
  tempCPUCore: 85
  tempVideo: 75
  tempDisk: 42
  fanSpeed: 2300  # n.b. for values over 1000 you need to parse them individually 
                  #      with the '?c' built in or freemarker will parse it as 1,000 instead
