system: laptop  # default value, overriden by freemarker java app
networkDevices:
  desktop:
    - name: enp0s25
      type: ethernet  
  laptop:
      - name: wlp4s0
        type: wifi
      - name: enp6s0
        type: ethernet
threshold:
  cpu: 90
  mem: 85
  swap: 70
  tempCPU: 78
  tempCPUCore: 85
  tempVideo: 75
  tempDisk: 42
  fanSpeed: 2300  # n.b. for values over 1000 you need to parse them individually 
                  #      with the '?c' built in or freemarker will parse it as 1,000 instead
