system: desktop         # default value, overriden by freemarker java app

networkDevices:
  desktop:
    - name: enp0s25
      type: ethernet
      maxUp: 3000       # speed in KiB
      maxDown: 60000
  laptop:
    - name: wlp4s0
      type: wifi
      maxUp: 8200
      maxDown: 55100
    - name: enp6s0
      type: ethernet
      maxUp: 3000
      maxDown: 60000
        
hardDisks:
  desktop:
    - device: sda
      readSpeed: 200000
      writeSpeed: 280000
      hwmonIndex: 0     # optional | linux hardware monitor index, ex. hwmon3
      partitions:
        - name: fedora
          path: /
          icon: root
        - name: home
          path: /home
          icon: home
    - device: sdb
      readSpeed: 6000
      writeSpeed: 250000
      hwmonIndex: 1
      partitions:
        - name: veronica
          path: /media/veronica
          icon: partition
    - device: sdd
      readSpeed: 6000
      writeSpeed: 250000
      hwmonIndex: 2
      partitions:
        - name: betty
          path: /media/betty
          icon: partition
    - device: sdg1
      readSpeed: 6000
      writeSpeed: 60000
      name: maxtor      # optional | name to append to the output file name, ex. disk-maxtor
      partitions:
        - name: maxtor
          path: /run/media/ernesto/MAXTOR
          icon: usbdrive

  laptop:
      - device: sda
        readSpeed: 60000
        writeSpeed: 60000
        partitions:
          - name: fedora
            path: /
            icon: root
          - name: home
            path: /home
            icon: home

threshold:
  cpu: 90
  mem: 85
  swap: 70
  tempCPU: 78
  tempCPUCore: 85
  tempVideo: 75
  tempDisk: 42
  fanSpeed: 2300  # n.b. for values over 1000 you need to parse them individually 
                  #      with the '?c' built in or freemarker will parse it as 1,000 instead
